//
// Created by packr on 12/8/2015.
//

#ifndef BACKLIGHTHANDLER_NATIVEIMAGEPROCESSING_H
#define BACKLIGHTHANDLER_NATIVEIMAGEPROCESSING_H


class NativeImageProcessing {

};


#endif //BACKLIGHTHANDLER_NATIVEIMAGEPROCESSING_H
